Check gh auth status

diff --git a/git-prs b/git-prs
--- a/git-prs
+++ b/git-prs
@@ -72,7 +72,11 @@ if ! type python >/dev/null 2>&1; then
 fi
 
 if ! type gh >/dev/null 2>&1; then
-    die "fatal: can't find GitHub CLI"
+    die "fatal: can't find gitHub cli"
+fi
+
+if ! gh auth status > /dev/null 2>&1; then
+    die "fatal: not authenticated"
 fi
 
 if [ -z "${GITHUB_USERNAME}" ]; then
