Don't use subshell to check for commands

diff --git a/git-branches b/git-branches
--- a/git-branches
+++ b/git-branches
@@ -8,6 +8,10 @@
 # - shows each local branch and how far ahead/behind they are from default branch on remote/origin
 # - sorted by last modified
 #
+# requires:
+#  - git (https://git-scm.com)
+#  - git-track-branches script
+#
 # instructions:
 #  - add this script to a directory on your PATH
 #  - make this script executable (chmod +x git-branches)
@@ -20,12 +24,16 @@ die () {
     exit 1
 }
 
-if [ ! -x "$(type -pP git)" ]; then
+if ! type git >/dev/null 2>&1; then
     die "fatal: can't find git"
 fi
 
 if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
     die "fatal: not a git repository"
+fi
+
+if ! type git-track-branchess >/dev/null 2>&1; then
+    die "fatal: can't find git-track-branches script"
 fi
 
 BRIGHT_YELLOW="\033[38;5;226m"
diff --git a/git-prs b/git-prs
--- a/git-prs
+++ b/git-prs
@@ -59,12 +59,24 @@ while getopts ":ah" opt; do
     esac
 done
 
-if [ -z "${GITHUB_USERNAME}" ]; then
-    die "fatal: 'GITHUB_USERNAME' environment variable not set"
+if ! type git >/dev/null 2>&1; then
+    die "fatal: can't find git"
 fi
 
-if [ ! -x "$(type -pP git)" ]; then
-    die "fatal: can't find git"
+if ! type jq >/dev/null 2>&1; then
+    die "fatal: can't find jq"
+fi
+
+if ! type python >/dev/null 2>&1; then
+    die "fatal: can't find python"
+fi
+
+if ! type gh >/dev/null 2>&1; then
+    die "fatal: can't find GitHub CLI"
+fi
+
+if [ -z "${GITHUB_USERNAME}" ]; then
+    die "fatal: 'GITHUB_USERNAME' environment variable not set"
 fi
 
 if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
@@ -73,18 +85,6 @@ fi
 
 if ! git remote --verbose | grep -q "github\.com"; then
     die "fatal: must have an origin on github.com"
-fi
-
-if [ ! -x "$(type -pP jq)" ]; then
-    die "fatal: can't find jq"
-fi
-
-if [ ! -x "$(type -pP python)" ]; then
-    die "fatal: can't find python"
-fi
-
-if [ ! -x "$(type -pP gh)" ]; then
-    die "fatal: can't find GitHub CLI"
 fi
 
 repo="${GITHUB_USERNAME}/$(basename $(basename $(git remote get-url origin)) '.git')"
diff --git a/git-syncrepo b/git-syncrepo
--- a/git-syncrepo
+++ b/git-syncrepo
@@ -11,6 +11,9 @@
 # - requires GitHub CLI (https://github.com/cli/cli/blob/trunk/docs/install_linux.md)
 # - must have parent repo set as default remote (run 'gh repo set-default')
 #
+# requires:
+#  - git (https://git-scm.com)
+#
 # instructions:
 #  - set an environment variable named 'GITHUB_USERNAME' with your GitHub
 #    account name (i.e.: 'export GITHUB_USERNAME=cgoldberg')
@@ -53,12 +56,16 @@ while getopts ":ah" opt; do
     esac
 done
 
-if [ -z "${GITHUB_USERNAME}" ]; then
-    die "fatal: 'GITHUB_USERNAME' environment variable not set"
+if ! type git >/dev/null 2>&1; then
+    die "fatal: can't find git"
 fi
 
-if [ ! -x "$(type -pP git)" ]; then
-    die "fatal: can't find git"
+if ! type gh >/dev/null 2>&1; then
+    die "fatal: can't find GitHub CLI"
+fi
+
+if [ -z "${GITHUB_USERNAME}" ]; then
+    die "fatal: 'GITHUB_USERNAME' environment variable not set"
 fi
 
 if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
@@ -67,10 +74,6 @@ fi
 
 if ! git remote --verbose | grep -q "github\.com"; then
     die "fatal: must have an origin on github.com"
-fi
-
-if [ ! -x "$(type -pP gh)" ]; then
-    die "fatal: can't find GitHub CLI"
 fi
 
 repo_name="$(basename $(basename $(git remote get-url origin)) '.git')"
